DROP TABLE dota_heroes;
CREATE TABLE IF NOT EXISTS dota_heroes(
    id int PRIMARY KEY,
    name varchar(255) UNIQUE,
    short_name varchar(255) UNIQUE,
    display_name varchar(255) UNIQUE
);
INSERT INTO dota_heroes(id, name, short_name, display_name) VALUES
    (1, 'npc_dota_hero_antimage', 'antimage', 'Anti-Mage'),
    (2, 'npc_dota_hero_axe', 'axe', 'Axe'),
    (3, 'npc_dota_hero_bane', 'bane', 'Bane'),
    (4, 'npc_dota_hero_bloodseeker', 'bloodseeker', 'Bloodseeker'),
    (5, 'npc_dota_hero_crystal_maiden', 'crystal_maiden', 'Crystal Maiden'),
    (6, 'npc_dota_hero_drow_ranger', 'drow_ranger', 'Drow Ranger'),
    (7, 'npc_dota_hero_earthshaker', 'earthshaker', 'Earthshaker'),
    (8, 'npc_dota_hero_juggernaut', 'juggernaut', 'Juggernaut'),
    (9, 'npc_dota_hero_mirana', 'mirana', 'Mirana'),
    (11, 'npc_dota_hero_nevermore', 'shadow_fiend', 'Shadow Fiend'),
    (10, 'npc_dota_hero_morphling', 'morphling', 'Morphling'),
    (12, 'npc_dota_hero_phantom_lancer', 'phantom_lancer', 'Phantom Lancer'),
    (13, 'npc_dota_hero_puck', 'puck', 'Puck'),
    (14, 'npc_dota_hero_pudge', 'pudge', 'Pudge'),
    (15, 'npc_dota_hero_razor', 'razor', 'Razor'),
    (16, 'npc_dota_hero_sand_king', 'sand_king', 'Sand King'),
    (17, 'npc_dota_hero_storm_spirit', 'storm_spirit', 'Storm Spirit'),
    (18, 'npc_dota_hero_sven', 'sven', 'Sven'),
    (19, 'npc_dota_hero_tiny', 'tiny', 'Tiny'),
    (20, 'npc_dota_hero_vengefulspirit', 'vengeful_spirit', 'Vengeful Spirit'),
    (21, 'npc_dota_hero_windrunner', 'windranger', 'Windranger'),
    (22, 'npc_dota_hero_zuus', 'zeus', 'Zeus'),
    (23, 'npc_dota_hero_kunkka', 'kunkka', 'Kunkka'),
    (25, 'npc_dota_hero_lina', 'lina', 'Lina'),
    (31, 'npc_dota_hero_lich', 'lich', 'Lich'),
    (26, 'npc_dota_hero_lion', 'lion', 'Lion'),
    (27, 'npc_dota_hero_shadow_shaman', 'shadow_shaman', 'Shadow Shaman'),
    (28, 'npc_dota_hero_slardar', 'slardar', 'Slardar'),
    (29, 'npc_dota_hero_tidehunter', 'tidehunter', 'Tidehunter'),
    (30, 'npc_dota_hero_witch_doctor', 'witch_doctor', 'Witch Doctor'),
    (32, 'npc_dota_hero_riki', 'riki', 'Riki'),
    (33, 'npc_dota_hero_enigma', 'enigma', 'Enigma'),
    (34, 'npc_dota_hero_tinker', 'tinker', 'Tinker'),
    (35, 'npc_dota_hero_sniper', 'sniper', 'Sniper'),
    (36, 'npc_dota_hero_necrolyte', 'necrophos', 'Necrophos'),
    (37, 'npc_dota_hero_warlock', 'warlock', 'Warlock'),
    (38, 'npc_dota_hero_beastmaster', 'beastmaster', 'Beastmaster'),
    (39, 'npc_dota_hero_queenofpain', 'queenofpain', 'Queen of Pain'),
    (40, 'npc_dota_hero_venomancer', 'venomancer', 'Venomancer'),
    (41, 'npc_dota_hero_faceless_void', 'faceless_void', 'Faceless Void'),
    (42, 'npc_dota_hero_skeleton_king', 'wraith_king', 'Wraith King'),
    (43, 'npc_dota_hero_death_prophet', 'death_prophet', 'Death Prophet'),
    (44, 'npc_dota_hero_phantom_assassin', 'phantom_assassin', 'Phantom Assassin'),
    (45, 'npc_dota_hero_pugna', 'pugna', 'Pugna'),
    (46, 'npc_dota_hero_templar_assassin', 'templar_assassin', 'Templar Assassin'),
    (47, 'npc_dota_hero_viper', 'viper', 'Viper'),
    (48, 'npc_dota_hero_luna', 'luna', 'Luna'),
    (49, 'npc_dota_hero_dragon_knight', 'dragon_knight', 'Dragon Knight'),
    (50, 'npc_dota_hero_dazzle', 'dazzle', 'Dazzle'),
    (51, 'npc_dota_hero_rattletrap', 'clockwerk', 'Clockwerk'),
    (52, 'npc_dota_hero_leshrac', 'leshrac', 'Leshrac'),
    (53, 'npc_dota_hero_furion', 'furion', 'Nature''s Prophet'),
    (54, 'npc_dota_hero_life_stealer', 'lifestealer', 'Lifestealer'),
    (55, 'npc_dota_hero_dark_seer', 'dark_seer', 'Dark Seer'),
    (56, 'npc_dota_hero_clinkz', 'clinkz', 'Clinkz'),
    (57, 'npc_dota_hero_omniknight', 'omniknight', 'Omniknight'),
    (58, 'npc_dota_hero_enchantress', 'enchantress', 'Enchantress'),
    (59, 'npc_dota_hero_huskar', 'huskar', 'Huskar'),
    (60, 'npc_dota_hero_night_stalker', 'night_stalker', 'Night Stalker'),
    (61, 'npc_dota_hero_broodmother', 'broodmother', 'Broodmother'),
    (62, 'npc_dota_hero_bounty_hunter', 'bounty_hunter', 'Bounty Hunter'),
    (63, 'npc_dota_hero_weaver', 'weaver', 'Weaver'),
    (64, 'npc_dota_hero_jakiro', 'jakiro', 'Jakiro'),
    (65, 'npc_dota_hero_batrider', 'batrider', 'Batrider'),
    (66, 'npc_dota_hero_chen', 'chen', 'Chen'),
    (67, 'npc_dota_hero_spectre', 'spectre', 'Spectre'),
    (69, 'npc_dota_hero_doom_bringer', 'doom', 'Doom'),
    (68, 'npc_dota_hero_ancient_apparition', 'ancient_apparition', 'Ancient Apparition'),
    (70, 'npc_dota_hero_ursa', 'ursa', 'Ursa'),
    (71, 'npc_dota_hero_spirit_breaker', 'spirit_breaker', 'Spirit Breaker'),
    (72, 'npc_dota_hero_gyrocopter', 'gyrocopter', 'Gyrocopter'),
    (73, 'npc_dota_hero_alchemist', 'alchemist', 'Alchemist'),
    (74, 'npc_dota_hero_invoker', 'invoker', 'Invoker'),
    (75, 'npc_dota_hero_silencer', 'silencer', 'Silencer'),
    (76, 'npc_dota_hero_obsidian_destroyer', 'outworld_devourer', 'Outworld Devourer'),
    (77, 'npc_dota_hero_lycan', 'lycan', 'Lycanthrope'),
    (78, 'npc_dota_hero_brewmaster', 'brewmaster', 'Brewmaster'),
    (79, 'npc_dota_hero_shadow_demon', 'shadow_demon', 'Shadow Demon'),
    (80, 'npc_dota_hero_lone_druid', 'lone_druid', 'Lone Druid'),
    (81, 'npc_dota_hero_chaos_knight', 'chaos_knight', 'Chaos Knight'),
    (82, 'npc_dota_hero_meepo', 'meepo', 'Meepo'),
    (83, 'npc_dota_hero_treant', 'treant', 'Treant Protector'),
    (84, 'npc_dota_hero_ogre_magi', 'ogre_magi', 'Ogre Magi'),
    (85, 'npc_dota_hero_undying', 'undying', 'Undying'),
    (86, 'npc_dota_hero_rubick', 'rubick', 'Rubick'),
    (87, 'npc_dota_hero_disruptor', 'disruptor', 'Disruptor'),
    (88, 'npc_dota_hero_nyx_assassin', 'nyx_assassin', 'Nyx Assassin'),
    (89, 'npc_dota_hero_naga_siren', 'naga_siren', 'Naga Siren'),
    (90, 'npc_dota_hero_keeper_of_the_light', 'keeper_of_the_light', 'Keeper of the Light'),
    (91, 'npc_dota_hero_wisp', 'wisp', 'Wisp'),
    (92, 'npc_dota_hero_visage', 'visage', 'Visage'),
    (93, 'npc_dota_hero_slark', 'slark', 'Slark'),
    (94, 'npc_dota_hero_medusa', 'medusa', 'Medusa'),
    (95, 'npc_dota_hero_troll_warlord', 'troll_warlord', 'Troll Warlord'),
    (96, 'npc_dota_hero_centaur', 'centaur', 'Centaur Warrunner'),
    (97, 'npc_dota_hero_magnataur', 'magnus', 'Magnus'),
    (98, 'npc_dota_hero_shredder', 'timbersaw', 'Timbersaw'),
    (99, 'npc_dota_hero_bristleback', 'bristleback', 'Bristleback'),
    (100, 'npc_dota_hero_tusk', 'tusk', 'Tusk'),
    (101, 'npc_dota_hero_skywrath_mage', 'skywrath_mage', 'Skywrath Mage'),
    (102, 'npc_dota_hero_abaddon', 'abaddon', 'Abaddon'),
    (103, 'npc_dota_hero_elder_titan', 'elder_titan', 'Elder Titan'),
    (104, 'npc_dota_hero_legion_commander', 'legion_commander', 'Legion Commander'),
    (105, 'npc_dota_hero_techies', 'techies', 'Techies'),
    (106, 'npc_dota_hero_ember_spirit', 'ember_spirit', 'Ember Spirit'),
    (107, 'npc_dota_hero_earth_spirit', 'earth_spirit', 'Earth Spirit'),
    (108, 'npc_dota_hero_abyssal_underlord', 'abyssal_underlord', 'Abyssal Underlord'),
    (109, 'npc_dota_hero_terrorblade', 'terrorblade', 'Terrorblade'),
    (110, 'npc_dota_hero_phoenix', 'phoenix', 'Phoenix'),
    (111, 'npc_dota_hero_oracle', 'oracle', 'Oracle'),
    (112, 'npc_dota_hero_winter_wyvern', 'winter_wyvern', 'Winter Wyvern'),
    (113, 'npc_dota_hero_arc_warden', 'arc_warden', 'Arc Warden'),
    (114, 'npc_dota_hero_monkey_king', 'monkey_king', 'Monkey King'),
    (119, 'npc_dota_hero_dark_willow', 'dark_willow', 'Dark Willow'),
    (120, 'npc_dota_hero_pangolier', 'pangolier', 'Pangolier'),
    (121, 'npc_dota_hero_grimstroke', 'grimstroke', 'Grimstroke'),
    (123, 'npc_dota_hero_hoodwink', 'hoodwink', 'Hoodwink'),
    (126, 'npc_dota_hero_void_spirit', 'void_spirit', 'Void Spirit'),
    (128, 'npc_dota_hero_snapfire', 'snapfire', 'Snapfire'),
    (129, 'npc_dota_hero_mars', 'mars', 'Mars'),
    (135, 'npc_dota_hero_dawnbreaker', 'dawnbreaker', 'Dawnbreaker');

DROP TABLE dota_items;
CREATE TABLE IF NOT EXISTS dota_items(
    id int PRIMARY KEY,
    name varchar(255) UNIQUE
);
INSERT INTO dota_items(id, name) VALUES
    (1, 'item_blink'),
    (600, 'item_overwhelming_blink'),
    (603, 'item_swift_blink'),
    (604, 'item_arcane_blink'),
    (606, 'item_recipe_arcane_blink'),
    (607, 'item_recipe_swift_blink'),
    (608, 'item_recipe_overwhelming_blink'),
    (2, 'item_blades_of_attack'),
    (3, 'item_broadsword'),
    (4, 'item_chainmail'),
    (5, 'item_claymore'),
    (6, 'item_helm_of_iron_will'),
    (7, 'item_javelin'),
    (8, 'item_mithril_hammer'),
    (9, 'item_platemail'),
    (10, 'item_quarterstaff'),
    (11, 'item_quelling_blade'),
    (237, 'item_faerie_fire'),
    (265, 'item_infused_raindrop'),
    (244, 'item_wind_lace'),
    (12, 'item_ring_of_protection'),
    (182, 'item_stout_shield'),
    (246, 'item_recipe_moon_shard'),
    (247, 'item_moon_shard'),
    (13, 'item_gauntlets'),
    (14, 'item_slippers'),
    (15, 'item_mantle'),
    (16, 'item_branches'),
    (17, 'item_belt_of_strength'),
    (18, 'item_boots_of_elves'),
    (19, 'item_robe'),
    (20, 'item_circlet'),
    (261, 'item_crown'),
    (21, 'item_ogre_axe'),
    (22, 'item_blade_of_alacrity'),
    (23, 'item_staff_of_wizardry'),
    (24, 'item_ultimate_orb'),
    (25, 'item_gloves'),
    (485, 'item_blitz_knuckles'),
    (26, 'item_lifesteal'),
    (473, 'item_voodoo_mask'),
    (27, 'item_ring_of_regen'),
    (279, 'item_ring_of_tarrasque'),
    (28, 'item_sobi_mask'),
    (29, 'item_boots'),
    (30, 'item_gem'),
    (31, 'item_cloak'),
    (32, 'item_talisman_of_evasion'),
    (33, 'item_cheese'),
    (34, 'item_magic_stick'),
    (35, 'item_recipe_magic_wand'),
    (36, 'item_magic_wand'),
    (37, 'item_ghost'),
    (38, 'item_clarity'),
    (216, 'item_enchanted_mango'),
    (39, 'item_flask'),
    (40, 'item_dust'),
    (41, 'item_bottle'),
    (42, 'item_ward_observer'),
    (43, 'item_ward_sentry'),
    (217, 'item_recipe_ward_dispenser'),
    (218, 'item_ward_dispenser'),
    (44, 'item_tango'),
    (241, 'item_tango_single'),
    (45, 'item_courier'),
    (286, 'item_flying_courier'),
    (46, 'item_tpscroll'),
    (47, 'item_recipe_travel_boots'),
    (219, 'item_recipe_travel_boots_2'),
    (48, 'item_travel_boots'),
    (220, 'item_travel_boots_2'),
    (49, 'item_recipe_phase_boots'),
    (50, 'item_phase_boots'),
    (51, 'item_demon_edge'),
    (52, 'item_eagle'),
    (53, 'item_reaver'),
    (54, 'item_relic'),
    (55, 'item_hyperstone'),
    (56, 'item_ring_of_health'),
    (57, 'item_void_stone'),
    (58, 'item_mystic_staff'),
    (59, 'item_energy_booster'),
    (60, 'item_point_booster'),
    (61, 'item_vitality_booster'),
    (593, 'item_fluffy_hat'),
    (62, 'item_recipe_power_treads'),
    (63, 'item_power_treads'),
    (653, 'item_recipe_grandmasters_glaive'),
    (655, 'item_grandmasters_glaive'),
    (64, 'item_recipe_hand_of_midas'),
    (65, 'item_hand_of_midas'),
    (66, 'item_recipe_oblivion_staff'),
    (67, 'item_oblivion_staff'),
    (533, 'item_recipe_witch_blade'),
    (534, 'item_witch_blade'),
    (68, 'item_recipe_pers'),
    (69, 'item_pers'),
    (70, 'item_recipe_poor_mans_shield'),
    (71, 'item_poor_mans_shield'),
    (731, 'item_satchel'),
    (72, 'item_recipe_bracer'),
    (73, 'item_bracer'),
    (74, 'item_recipe_wraith_band'),
    (75, 'item_wraith_band'),
    (76, 'item_recipe_null_talisman'),
    (77, 'item_null_talisman'),
    (78, 'item_recipe_mekansm'),
    (79, 'item_mekansm'),
    (80, 'item_recipe_vladmir'),
    (81, 'item_vladmir'),
    (85, 'item_recipe_buckler'),
    (86, 'item_buckler'),
    (87, 'item_recipe_ring_of_basilius'),
    (88, 'item_ring_of_basilius'),
    (268, 'item_recipe_holy_locket'),
    (269, 'item_holy_locket'),
    (89, 'item_recipe_pipe'),
    (90, 'item_pipe'),
    (91, 'item_recipe_urn_of_shadows'),
    (92, 'item_urn_of_shadows'),
    (93, 'item_recipe_headdress'),
    (94, 'item_headdress'),
    (95, 'item_recipe_sheepstick'),
    (96, 'item_sheepstick'),
    (97, 'item_recipe_orchid'),
    (98, 'item_orchid'),
    (245, 'item_recipe_bloodthorn'),
    (250, 'item_bloodthorn'),
    (251, 'item_recipe_echo_sabre'),
    (252, 'item_echo_sabre'),
    (99, 'item_recipe_cyclone'),
    (100, 'item_cyclone'),
    (612, 'item_recipe_wind_waker'),
    (610, 'item_wind_waker'),
    (233, 'item_recipe_aether_lens'),
    (232, 'item_aether_lens'),
    (101, 'item_recipe_force_staff'),
    (102, 'item_force_staff'),
    (262, 'item_recipe_hurricane_pike'),
    (263, 'item_hurricane_pike'),
    (103, 'item_recipe_dagon'),
    (197, 'item_recipe_dagon_2'),
    (198, 'item_recipe_dagon_3'),
    (199, 'item_recipe_dagon_4'),
    (200, 'item_recipe_dagon_5'),
    (104, 'item_dagon'),
    (201, 'item_dagon_2'),
    (202, 'item_dagon_3'),
    (203, 'item_dagon_4'),
    (204, 'item_dagon_5'),
    (105, 'item_recipe_necronomicon'),
    (191, 'item_recipe_necronomicon_2'),
    (192, 'item_recipe_necronomicon_3'),
    (106, 'item_necronomicon'),
    (193, 'item_necronomicon_2'),
    (194, 'item_necronomicon_3'),
    (107, 'item_recipe_ultimate_scepter'),
    (108, 'item_ultimate_scepter'),
    (270, 'item_recipe_ultimate_scepter_2'),
    (271, 'item_ultimate_scepter_2'),
    (727, 'item_ultimate_scepter_roshan'),
    (609, 'item_aghanims_shard'),
    (725, 'item_aghanims_shard_roshan'),
    (109, 'item_recipe_refresher'),
    (110, 'item_refresher'),
    (111, 'item_recipe_assault'),
    (112, 'item_assault'),
    (113, 'item_recipe_heart'),
    (114, 'item_heart'),
    (115, 'item_recipe_black_king_bar'),
    (116, 'item_black_king_bar'),
    (117, 'item_aegis'),
    (118, 'item_recipe_shivas_guard'),
    (119, 'item_shivas_guard'),
    (120, 'item_recipe_bloodstone'),
    (121, 'item_bloodstone'),
    (122, 'item_recipe_sphere'),
    (123, 'item_sphere'),
    (221, 'item_recipe_lotus_orb'),
    (226, 'item_lotus_orb'),
    (222, 'item_recipe_meteor_hammer'),
    (223, 'item_meteor_hammer'),
    (224, 'item_recipe_nullifier'),
    (225, 'item_nullifier'),
    (255, 'item_recipe_aeon_disk'),
    (256, 'item_aeon_disk'),
    (258, 'item_recipe_kaya'),
    (259, 'item_kaya'),
    (369, 'item_trident'),
    (276, 'item_combo_breaker'),
    (260, 'item_refresher_shard'),
    (266, 'item_recipe_spirit_vessel'),
    (267, 'item_spirit_vessel'),
    (124, 'item_recipe_vanguard'),
    (125, 'item_vanguard'),
    (243, 'item_recipe_crimson_guard'),
    (242, 'item_crimson_guard'),
    (126, 'item_recipe_blade_mail'),
    (127, 'item_blade_mail'),
    (128, 'item_recipe_soul_booster'),
    (129, 'item_soul_booster'),
    (130, 'item_recipe_hood_of_defiance'),
    (131, 'item_hood_of_defiance'),
    (691, 'item_recipe_eternal_shroud'),
    (692, 'item_eternal_shroud'),
    (132, 'item_recipe_rapier'),
    (133, 'item_rapier'),
    (134, 'item_recipe_monkey_king_bar'),
    (135, 'item_monkey_king_bar'),
    (136, 'item_recipe_radiance'),
    (137, 'item_radiance'),
    (138, 'item_recipe_butterfly'),
    (139, 'item_butterfly'),
    (140, 'item_recipe_greater_crit'),
    (141, 'item_greater_crit'),
    (142, 'item_recipe_basher'),
    (143, 'item_basher'),
    (144, 'item_recipe_bfury'),
    (145, 'item_bfury'),
    (146, 'item_recipe_manta'),
    (147, 'item_manta'),
    (148, 'item_recipe_lesser_crit'),
    (149, 'item_lesser_crit'),
    (234, 'item_recipe_dragon_lance'),
    (236, 'item_dragon_lance'),
    (150, 'item_recipe_armlet'),
    (151, 'item_armlet'),
    (183, 'item_recipe_invis_sword'),
    (152, 'item_invis_sword'),
    (248, 'item_recipe_silver_edge'),
    (249, 'item_silver_edge'),
    (153, 'item_recipe_sange_and_yasha'),
    (154, 'item_sange_and_yasha'),
    (272, 'item_recipe_kaya_and_sange'),
    (273, 'item_kaya_and_sange'),
    (274, 'item_recipe_yasha_and_kaya'),
    (277, 'item_yasha_and_kaya'),
    (155, 'item_recipe_satanic'),
    (156, 'item_satanic'),
    (157, 'item_recipe_mjollnir'),
    (158, 'item_mjollnir'),
    (159, 'item_recipe_skadi'),
    (160, 'item_skadi'),
    (161, 'item_recipe_sange'),
    (162, 'item_sange'),
    (163, 'item_recipe_helm_of_the_dominator'),
    (164, 'item_helm_of_the_dominator'),
    (633, 'item_recipe_helm_of_the_overlord'),
    (635, 'item_helm_of_the_overlord'),
    (165, 'item_recipe_maelstrom'),
    (166, 'item_maelstrom'),
    (1565, 'item_recipe_gungir'),
    (1466, 'item_gungir'),
    (167, 'item_recipe_desolator'),
    (168, 'item_desolator'),
    (169, 'item_recipe_yasha'),
    (170, 'item_yasha'),
    (171, 'item_recipe_mask_of_madness'),
    (172, 'item_mask_of_madness'),
    (173, 'item_recipe_diffusal_blade'),
    (174, 'item_diffusal_blade'),
    (175, 'item_recipe_ethereal_blade'),
    (176, 'item_ethereal_blade'),
    (177, 'item_recipe_soul_ring'),
    (178, 'item_soul_ring'),
    (179, 'item_recipe_arcane_boots'),
    (180, 'item_arcane_boots'),
    (228, 'item_recipe_octarine_core'),
    (235, 'item_octarine_core'),
    (181, 'item_orb_of_venom'),
    (240, 'item_blight_stone'),
    (640, 'item_recipe_orb_of_corrosion'),
    (569, 'item_orb_of_corrosion'),
    (599, 'item_recipe_falcon_blade'),
    (596, 'item_falcon_blade'),
    (597, 'item_recipe_mage_slayer'),
    (598, 'item_mage_slayer'),
    (184, 'item_recipe_ancient_janggo'),
    (185, 'item_ancient_janggo'),
    (186, 'item_recipe_medallion_of_courage'),
    (187, 'item_medallion_of_courage'),
    (227, 'item_recipe_solar_crest'),
    (229, 'item_solar_crest'),
    (188, 'item_smoke_of_deceit'),
    (257, 'item_tome_of_knowledge'),
    (189, 'item_recipe_veil_of_discord'),
    (190, 'item_veil_of_discord'),
    (230, 'item_recipe_guardian_greaves'),
    (231, 'item_guardian_greaves'),
    (205, 'item_recipe_rod_of_atos'),
    (206, 'item_rod_of_atos'),
    (238, 'item_recipe_iron_talon'),
    (239, 'item_iron_talon'),
    (207, 'item_recipe_abyssal_blade'),
    (208, 'item_abyssal_blade'),
    (209, 'item_recipe_heavens_halberd'),
    (210, 'item_heavens_halberd'),
    (211, 'item_recipe_ring_of_aquila'),
    (212, 'item_ring_of_aquila'),
    (213, 'item_recipe_tranquil_boots'),
    (214, 'item_tranquil_boots'),
    (215, 'item_shadow_amulet'),
    (253, 'item_recipe_glimmer_cape'),
    (254, 'item_glimmer_cape'),
    (1021, 'item_river_painter'),
    (1022, 'item_river_painter2'),
    (1023, 'item_river_painter3'),
    (1024, 'item_river_painter4'),
    (1025, 'item_river_painter5'),
    (1026, 'item_river_painter6'),
    (1027, 'item_river_painter7'),
    (1028, 'item_mutation_tombstone'),
    (1029, 'item_super_blink'),
    (1030, 'item_pocket_tower'),
    (1032, 'item_pocket_roshan'),
    (287, 'item_keen_optic'),
    (288, 'item_grove_bow'),
    (289, 'item_quickening_charm'),
    (290, 'item_philosophers_stone'),
    (291, 'item_force_boots'),
    (292, 'item_desolator_2'),
    (293, 'item_phoenix_ash'),
    (294, 'item_seer_stone'),
    (295, 'item_greater_mango'),
    (302, 'item_elixer'),
    (297, 'item_vampire_fangs'),
    (829, 'item_force_field'),
    (833, 'item_tree_processor'),
    (834, 'item_black_powder_bag'),
    (849, 'item_mechanical_arm'),
    (298, 'item_craggy_coat'),
    (299, 'item_greater_faerie_fire'),
    (300, 'item_timeless_relic'),
    (301, 'item_mirror_shield'),
    (303, 'item_recipe_ironwood_tree'),
    (304, 'item_ironwood_tree'),
    (328, 'item_mango_tree'),
    (305, 'item_royal_jelly'),
    (306, 'item_pupils_gift'),
    (307, 'item_tome_of_aghanim'),
    (308, 'item_repair_kit'),
    (309, 'item_mind_breaker'),
    (310, 'item_third_eye'),
    (311, 'item_spell_prism'),
    (325, 'item_princes_knife'),
    (330, 'item_witless_shako'),
    (334, 'item_imp_claw'),
    (335, 'item_flicker'),
    (336, 'item_spy_gadget'),
    (326, 'item_spider_legs'),
    (327, 'item_helm_of_the_undying'),
    (329, 'item_recipe_vambrace'),
    (331, 'item_vambrace'),
    (312, 'item_horizon'),
    (313, 'item_fusion_rune'),
    (354, 'item_ocean_heart'),
    (355, 'item_broom_handle'),
    (356, 'item_trusty_shovel'),
    (357, 'item_nether_shawl'),
    (358, 'item_dragon_scale'),
    (359, 'item_essence_ring'),
    (360, 'item_clumsy_net'),
    (361, 'item_enchanted_quiver'),
    (362, 'item_ninja_gear'),
    (363, 'item_illusionsts_cape'),
    (364, 'item_havoc_hammer'),
    (365, 'item_panic_button'),
    (366, 'item_apex'),
    (367, 'item_ballista'),
    (368, 'item_woodland_striders'),
    (275, 'item_recipe_trident'),
    (370, 'item_demonicon'),
    (317, 'item_recipe_fallen_sky'),
    (371, 'item_fallen_sky'),
    (372, 'item_pirate_hat'),
    (373, 'item_dimensional_doorway'),
    (374, 'item_ex_machina'),
    (375, 'item_faded_broach'),
    (376, 'item_paladin_sword'),
    (377, 'item_minotaur_horn'),
    (378, 'item_orb_of_destruction'),
    (379, 'item_the_leveller'),
    (349, 'item_arcane_ring'),
    (381, 'item_titan_sliver'),
    (565, 'item_chipped_vest'),
    (566, 'item_wizard_glass'),
    (570, 'item_gloves_of_travel'),
    (573, 'item_elven_tunic'),
    (574, 'item_cloak_of_flames'),
    (575, 'item_venom_gland'),
    (571, 'item_trickster_cloak'),
    (576, 'item_gladiator_helm'),
    (577, 'item_possessed_mask'),
    (578, 'item_ancient_perseverance'),
    (637, 'item_star_mace'),
    (638, 'item_penta_edged_sword'),
    (582, 'item_oakheart'),
    (674, 'item_warhammer'),
    (680, 'item_bullwhip'),
    (675, 'item_psychic_headband'),
    (676, 'item_ceremonial_robe'),
    (686, 'item_quicksilver_amulet'),
    (677, 'item_book_of_shadows'),
    (678, 'item_giants_ring'),
    (679, 'item_vengeances_shadow'),
    (585, 'item_stormcrafter'),
    (588, 'item_overflowing_elixir'),
    (589, 'item_mysterious_hat'),
    (824, 'item_assassins_dagger'),
    (825, 'item_ascetic_cap'),
    (826, 'item_sample_picker'),
    (827, 'item_icarus_wings'),
    (828, 'item_misericorde'),
    (836, 'item_light_robes'),
    (837, 'item_heavy_blade'),
    (838, 'item_unstable_wand'),
    (839, 'item_fortitude_ring'),
    (840, 'item_pogo_stick'),
    (835, 'item_paintball');

DROP TABLE dota_pro_teams;
CREATE TABLE IF NOT EXISTS dota_pro_teams(
    id bigint PRIMARY KEY,
    name varchar(255) UNIQUE,
    ti boolean
);
INSERT INTO dota_pro_teams(id, name, ti) VALUES
    (5, 'Invictus Gaming', TRUE),
    (15, 'PSG.LGD', TRUE),
    (36, 'Natus Vincere', FALSE),
    (39, 'Evil Geniuses', TRUE),
    (2163, 'Team Liquid', FALSE),
    (111474, 'Alliance', TRUE),
    (350190, 'Fnatic', TRUE),
    (543897, 'Mineski', FALSE),
    (726228, 'Vici Gaming', TRUE),
    (1838315, 'Team Secret', TRUE),
    (1883502, 'Virtus.Pro', TRUE),
    (2108395, 'TNC Predator', FALSE),
    (2586976, 'OG', TRUE),
    (2626685, 'Keen Gaming', FALSE),
    (2672298, 'Infamous', FALSE),
    (6209166, 'Team Aster', TRUE),
    (6209804, 'Royal Never Give Up', FALSE),
    (6214538, 'Newbee', FALSE),
    (6214973, 'Ninjas in Pyjamas', FALSE),
    (6666989, 'Chaos Esports Club',  FALSE),
    (7119388, 'Team Spirit',  TRUE),
    (7390454, 'Quincy Crew',  TRUE),
    (7391077, 'Thunder Predator',  TRUE),
    (8204512, 'Elephant',  TRUE),
    (8214850, 'T1',  TRUE),
    (8254400, 'beastcoast',  TRUE),
    (8255756, 'SG esports',  TRUE),
    (8260983, 'Undying', TRUE);

DROP TABLE dota_pro_players;
CREATE TABLE IF NOT EXISTS dota_pro_players(
    account_id bigint PRIMARY KEY,
    nickname varchar(255),
    name varchar(255) UNIQUE
);
INSERT INTO dota_pro_players(account_id, nickname, name) VALUES
    (125581247, 'Ame', 'Wang Chunyu'),
    (106863163, 'Maybe', 'Lu Yao'),
    (94738847, 'Chalice', 'Yang Shenyi'),
    (101695162, 'fy', 'Xu Linsen'),
    (94296097, 'xNova', 'Yap Jian Wei'),

    (114619230, 'Crystallize', 'Vladislav Krystanek'),
    (171981096, 'MagicaL', 'Idan Vardanian'),
    (234699894, 'Blizzy', 'Evgeniy Ree'),
    (111030315, 'Zayac', 'Bakyt Emilzhanov'),
    (117421467, 'SoNNeikO', 'Akbar Butaev'),

    (86745912, 'Arteezy', 'Artour Babaev'),
    (41231571, 's4', 'Gustav Magnusson'),
    (25907144, 'Cr1t-', 'Andreas Nielsen'),
    (94155156, 'Fly', 'Tal Aizik'),

    (105248644, 'Miracle-', 'Amer Al-Barkawi'),
    (86700461, 'w33', 'Aliwi Omar'),
    (34505203, 'MinD_ContRoL', 'Ivan Ivanov'),
    (101356886, 'GH', 'Maroun Merhej'),
    (82262664, 'KuroKy', 'Kuro Salehi Takhasomi'),

    (152962063, 'miCKe', 'Michael Vu'),
    (86738694, 'qojqva', 'Maximilian Bröcker'),
    (77490514, 'Boxi', 'Samuel Svahn'),
    (401792574, 'Taiga', 'Tommy Le'),
    (54580962, 'iNSaNiA', 'Aydin Sarkohi'),

    (100471531, 'Jabz', 'Anucha Jirawong'),
    (154715080, 'Abed', 'Abed Azel Yusop'),
    (84772440, 'iceiceice', 'Daryl Koh Pei Xiang'),
    (102099826, 'Dj', 'Djardel Mampusti'),
    (145550466, 'DuBu', 'Kim Doo-young'),

    (412753955, 'Nikobaby', 'Nikolay Nikolov'),
    (113457795, 'Moon', 'Kam Boon Seng'),
    (87012746, 'kpii', 'Damien Chok'),
    (192914280, 'Bimbi', 'Ryan Jay Qui'),
    (91443418, 'ninjaboogie', 'Michael Ross Jr.'),

    (137193239, 'Paparazi', 'Zhang Chengjun'),
    (107803494, 'Ori', 'Zeng Jiaoyang'),
    (139937922, 'Yang', 'Zhou Haiyang'),
    (182331313, 'Fade', 'Pan Yi'),
    (143693439, 'Dy', 'Ding Cong'),

    (121769650, 'Nisha', 'Michał Jankowski'),
    (116585378, 'MidOne', 'Yeik Nai Zheng'),
    (73562326, 'zai', 'Ludwig Wåhlberg'),
    (89117038, 'YapzOr', 'Yazied Jaradat'),
    (87278757, 'Puppey', 'Clement Ivanov'),

    (132851371, 'RAMZES666', 'Roman Kushnarev'),
    (106573901, 'No[o]ne', 'Vladimir Minenko'),
    (92423451, '9pasha', 'Pavel Khvastunov'),
    (159020918, 'RodjER', 'Vladimir Nikogosyan'),
    (134556694, 'Solo', 'Alexei Berezin'),

    (152545459, 'Gabbi', 'Kim Villafuerte'),
    (164532005, 'Armel', 'Armel Paul Tabios'),
    (184950344, 'Kuku', 'Carlo Palad'),
    (155494381, 'Tims', 'Timothy Randrup'),
    (173476224, 'eyyou', 'Nico Barcelon'),

    (111620041, 'SumaiL', 'Syed Sumail Hassan'),
    (94054712, 'Topson', 'Topias Taavitsainen'),
    (88271237, 'Ceb', 'Sébastien Debs'),
    (103735745, 'Saksa', 'Martin Sazdov'),
    (19672354, 'N0tail', 'Johan Sundstein'),

    (135878232, 'old chicken', 'Wang Zhiyong'),
    (255219872, '一', 'Zhai Jingkai'),
    (134276083, 'eLeVeN', 'Ren Yangwei'),
    (139876032, 'Kaka', 'Hu Liangzhi'),
    (397462905, 'dark', 'Song Runxi'),

    (164685175, 'K1', 'Hector Antonio Rodriguez'),
    (153836240, 'Chris Luck', 'Jean Pierre Gonzales'),
    (292921272, 'Wisper', 'Adrian Cespedes Dobles'),
    (157989498, 'Scofield', 'Elvis De la Cruz Peña'),
    (119631156, 'Stinger', 'Steven Vargas'),

    (148215639, 'Monet', 'Du Peng'),
    (139822354, 'Setsu', 'Gao Zhenxiong'),
    (186627166, 'Flyby', 'Su Lei'),
    (89423756, 'LaNm', 'Zhang Zhicheng'),
    (119576842, 'ah fu', 'Tue Soon Chuan'),

    (108452107, 'YawaR', 'Yawar Hassan'),
    (221666230, 'CCnC', 'Quinn Callahan'),
    (10366616, 'Sneyking', 'Jingjun Wu'),
    (86726887, 'MSS', 'Arif Anwar'),
    (6922000, 'pieliedie', 'Johan Åström'),

    (97590558, 'Ace', 'Marcus Hoelgaard'),
    (86799300, 'Fata', 'Adrian Trinks'),
    (86698277, '33', 'Neta Shapira'),
    (86727555, 'ppd', 'Peter Dager'),

    (142139318, 'vtFαded', 'Cheng Jia Hao'),
    (72312627, 'MATUMBAMAN', 'Lasse Urpalainen'),
    (169025618, 'KheZu', 'Maurice Gutmann'),
    (98172857, 'MiLAN', 'Milan Kozomara'),
    (87382579, 'MISERY', 'Rasmus Berth Filipsen');

CREATE TABLE IF NOT EXISTS group_stage(
    team_id bigint PRIMARY KEY references dota_pro_teams(id),
    group_number int NOT NULL,
    color varchar(255) NOT NULL,
    wins int NOT NULL,
    loses int NOT NULL,
    position int NOT NULL
);
