nb_pick=table;
for j=1:height(hero)
    pick=0;
    testnbpick=table;
    testnbpick.id=hero.hero_id(j);
    testnbpick.name=hero.hero_name(j);
    for i=1:height(matchvalvetn)
        if (matchvalvetn.rabiant_p1(i)==hero.hero_id(j) ||...
                matchvalvetn.rabiant_p1(i)==hero.hero_id(j) ||...
                matchvalvetn.rabiant_p2(i)==hero.hero_id(j) ||...
                matchvalvetn.rabiant_p3(i)==hero.hero_id(j) ||...
                matchvalvetn.rabiant_p4(i)==hero.hero_id(j) ||...
                matchvalvetn.rabiant_p5(i)==hero.hero_id(j) ||...
                matchvalvetn.dire_p1(i)==hero.hero_id(j) ||...
                matchvalvetn.dire_p2(i)==hero.hero_id(j) ||...
                matchvalvetn.dire_p3(i)==hero.hero_id(j) ||...
                matchvalvetn.dire_p4(i)==hero.hero_id(j) ||...
                matchvalvetn.dire_p5(i)==hero.hero_id(j))==1
            pick=pick+1;
        end
    end
    testnbpick.nb_pick=pick;
    nb_pick=[nb_pick;testnbpick];
end